#ifndef codechef_h
#define codechef_h

#include "competitive.h"

// Extern functions
namespace ADASTAIR { extern int main(); } using namespace ADASTAIR; int ADASTAIR::main();

std::map<string, function<void()>> process = {
    {"ADASTAIR", ADASTAIR::main}
};

const string sign = 
    "/*\n"
    " * Autogenerated File\n"
    " * @ Prakhar Dhama\n"
    " * https://github.com/prakhardhama/VSCode-Codechef\n"
    " */";
#endif